{
 "title": "Credible Layer sidecar",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Sidecar pods",
    "query": {
     "query": "label_values({\"$namespace\"=\"$namespace\"},pod)"
    }
   },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "Processing times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current height",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sidecar_current_height{pod=~\"${pod:regex}\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks per second",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sidecar_current_height{pod=~\"${pod:regex}\", namespace=~\"$namespace\"}[$__range])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "BlockEnv received distribution",
   "type": "histogram",
   "description": "Shows how the distribution of how long it takes between receiving blockenvs across all pods",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (pod, quantile) (\n  sidecar_block_processing_duration_seconds{\n    namespace=~\"$namespace\",\n    pod=~\"${pod:regex}\",\n    quantile=~\"0.5|0.95|0.99\"\n  }\n)",
     "legendFormat": "{{pod}} - p{{quantile}}"
    }
   ]
  },
  {
   "title": "Sidecar min required height",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sidecar_cache_min_required_height{namespace=~\"$namespace\", pod=~\"${pod:regex}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cache stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Sidecar cache invalidations",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sidecar_cache_invalidations{namespace=~\"$namespace\", pod=~\"${pod:regex}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Basic Ref counter",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "sidecar_cache_basic_ref_counter{namespace=~\"$namespace\", pod=~\"${pod:regex}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "storage ref counter",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sidecar_cache_storage_ref_counter{namespace=~\"$namespace\", pod=~\"${pod:regex}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Block hash counter",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "expr": "sidecar_cache_block_hash_ref_counter{namespace=~\"$namespace\", pod=~\"${pod:regex}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Sidecar cache invalidations time ",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sidecar_cache_invalidations_time_seconds{namespace=~\"$namespace\", pod=~\"${pod:regex}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BasicRef time distribution",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 21 },
   "targets": [
    {
     "expr": "sidecar_cache_basic_ref_duration{namespace=~\"$namespace\", pod=~\"${pod:regex}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "storage ref time distribution",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sidecar_cache_storage_ref_duration{namespace=~\"$namespace\", pod=~\"${pod:regex}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "block hash time distribution",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 21 },
   "targets": [
    {
     "expr": "sidecar_cache_block_hash_ref_duration{namespace=~\"$namespace\", pod=~\"${pod:regex}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Block stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Gas used per block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sidecar_block_gas_used{namespace=~\"$namespace\", pod=~\"${pod:regex}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Block gas average",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (pod) (\n  avg_over_time(sidecar_block_gas_used{namespace=~\"$namespace\", pod=~\"${pod:regex}\"}[$__range])\n)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Assertion gas per block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sidecar_assertion_gas_per_block{namespace=~\"$namespace\", pod=~\"${pod:regex}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Assertion gas average",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (pod) (\n  avg_over_time(sidecar_assertion_gas_per_block{namespace=~\"$namespace\", pod=~\"${pod:regex}\"}[$__range])\n)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Assertion functions per block",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 36 },
   "targets": [
    {
     "expr": "sidecar_assertions_per_block{namespace=~\"$namespace\", pod=~\"${pod:regex}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Transaction stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Transactions considered per block",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sidecar_transactions_considered{namespace=~\"$namespace\", pod=~\"${pod:regex}\"}",
     "legendFormat": "{{pod}} - p{{quantile}}"
    }
   ]
  },
  {
   "title": "Transactions simulated",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 42 },
   "targets": [
    {
     "expr": "sidecar_transactions_simulated{namespace=~\"$namespace\", pod=~\"${pod:regex}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transactions simulated per second",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sidecar_transactions_simulated{namespace=~\"$namespace\", pod=~\"${pod:regex}\"}[$__range])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Successful transactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sidecar_transactions_simulated_success{namespace=~\"$namespace\", pod=~\"${pod:regex}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Failed transactions",
   "type": "timeseries",
   "description": "(reverts, etc...)",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 48 },
   "targets": [
    {
     "expr": "sidecar_transactions_simulated_failure{namespace=~\"$namespace\", pod=~\"${pod:regex}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Invalidating transactions",
   "type": "timeseries",
   "description": "Transactions that failed assertions",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 48 },
   "targets": [
    {
     "expr": "sidecar_invalidated_transactions{namespace=~\"$namespace\", pod=~\"${pod:regex}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Transaction analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Top 50 assertion gas transactions",
   "type": "table",
   "description": "Top 50 transactions by assertion gas",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "topk(\n  50,\n  avg by (tx_hash) (\n    sidecar_assertion_gas_per_transaction{namespace=~\"$namespace\"}\n  )\n)\n",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Top 50 longest processing transactions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "topk(\n  50,\n  max by (tx_hash) (\n    max_over_time(sidecar_transaction_processing_duration{namespace=~\"$namespace\", pod=~\"${pod:regex}\"}[$__range])\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Assertion gas average",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (pod) (\n  avg_over_time(sidecar_gas_per_assertion{namespace=~\"$namespace\", pod=~\"${pod:regex}\"}[$__range])\n)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Assertion gas median (p50)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (pod) (\n  quantile_over_time(\n    0.5,\n    sidecar_gas_per_assertion{namespace=~\"$namespace\", pod=~\"${pod:regex}\"}[$__range]\n  )\n)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}