//! # PoC 3 — clap + manual merge (recommended approach)
//!
//! Demonstrates CLI > ENV > FILE precedence using:
//! - `clap::Parser` with `env = "SIDECAR_..."` on every field  (handles CLI + ENV)
//! - A `PocFileConfig` deserialized from JSON                  (handles FILE)
//! - A `merge()` function that uses `ArgMatches::value_source()` to pick the winner
//!
//! ## Key advantages over config-rs / figment
//! - **Zero new deps** — clap is already in the workspace
//! - **Per-field `env`** — matches existing flat `SIDECAR_*` naming, no separator ambiguity
//! - **`ValueSource` provenance** — we can tell exactly WHERE each value came from
//! - **`--help` auto-generation** — env var names shown automatically
//! - **No macro magic** — straightforward Rust, easy to debug
//!
//! ## `--help` output (auto-generated by clap)
//!
//! ```text
//! $ sidecar --help
//! Credible layer sidecar (PoC)
//!
//! Usage: sidecar [OPTIONS]
//!
//! Options:
//!       --chain-id <CHAIN_ID>
//!           Chain ID [env: SIDECAR_CHAIN_ID=]
//!       --spec-id <SPEC_ID>
//!           EVM specification (e.g. CANCUN) [env: SIDECAR_CHAIN_SPEC_ID=]
//!       --assertion-gas-limit <ASSERTION_GAS_LIMIT>
//!           Gas limit for assertion execution [env: SIDECAR_ASSERTION_GAS_LIMIT=]
//!       --assertion-da-rpc-url <ASSERTION_DA_RPC_URL>
//!           HTTP URL of the assertion DA [env: SIDECAR_ASSERTION_DA_RPC_URL=]
//!       --event-source-url <EVENT_SOURCE_URL>
//!           URL of the event source for assertion events [env: SIDECAR_EVENT_SOURCE_URL=]
//!       --state-oracle <STATE_ORACLE>
//!           Contract address of the state oracle [env: SIDECAR_STATE_ORACLE=]
//!       --state-oracle-deployment-block <STATE_ORACLE_DEPLOYMENT_BLOCK>
//!           Block number of the state oracle deployment [env: SIDECAR_STATE_ORACLE_DEPLOYMENT_BLOCK=]
//!       --config-file-path <CONFIG_FILE_PATH>
//!           Path to JSON config file [env: CONFIG_FILE_PATH=]
//!   -h, --help
//!           Print help
//! ```

use clap::{Parser, parser::ValueSource};
use serde::Deserialize;
use std::fmt;

// ---------------------------------------------------------------------------
// 1. CLI args — clap handles both CLI flags AND env vars
// ---------------------------------------------------------------------------
// Every field is `Option<T>` so we can distinguish "not provided" from "provided".
// clap's `env = "..."` attribute means `--help` will show the env var name automatically.

/// Credible layer sidecar (PoC)
#[derive(Debug, Parser)]
#[command(name = "sidecar", about = "Credible layer sidecar (PoC)")]
pub struct PocCliArgs {
    /// Chain ID
    #[arg(long, env = "SIDECAR_CHAIN_ID")]
    pub chain_id: Option<u64>,

    /// EVM specification (e.g. CANCUN)
    #[arg(long, env = "SIDECAR_CHAIN_SPEC_ID")]
    pub spec_id: Option<String>,

    /// Gas limit for assertion execution
    #[arg(long, env = "SIDECAR_ASSERTION_GAS_LIMIT")]
    pub assertion_gas_limit: Option<u64>,

    /// HTTP URL of the assertion DA
    #[arg(long, env = "SIDECAR_ASSERTION_DA_RPC_URL")]
    pub assertion_da_rpc_url: Option<String>,

    /// URL of the event source for assertion events
    #[arg(long, env = "SIDECAR_EVENT_SOURCE_URL")]
    pub event_source_url: Option<String>,

    /// Contract address of the state oracle
    #[arg(long, env = "SIDECAR_STATE_ORACLE")]
    pub state_oracle: Option<String>,

    /// Block number of the state oracle deployment
    #[arg(long, env = "SIDECAR_STATE_ORACLE_DEPLOYMENT_BLOCK")]
    pub state_oracle_deployment_block: Option<u64>,

    /// Path to JSON config file
    #[arg(long, env = "CONFIG_FILE_PATH")]
    pub config_file_path: Option<String>,
}

// ---------------------------------------------------------------------------
// 2. File config — mirrors the existing JSON shape (nested chain / credible)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Deserialize, Default)]
pub struct PocFileConfig {
    pub chain: Option<PocChainFile>,
    pub credible: Option<PocCredibleFile>,
}

#[derive(Debug, Clone, Deserialize, Default)]
pub struct PocChainFile {
    pub chain_id: Option<u64>,
    pub spec_id: Option<String>,
}

#[derive(Debug, Clone, Deserialize, Default)]
pub struct PocCredibleFile {
    pub assertion_gas_limit: Option<u64>,
    pub assertion_da_rpc_url: Option<String>,
    pub event_source_url: Option<String>,
    pub state_oracle: Option<String>,
    pub state_oracle_deployment_block: Option<u64>,
}

// ---------------------------------------------------------------------------
// 3. Resolved config — the final, fully-validated types
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PocConfig {
    pub chain_id: Sourced<u64>,
    pub spec_id: Sourced<String>,
    pub assertion_gas_limit: Sourced<u64>,
    pub assertion_da_rpc_url: Sourced<String>,
    pub event_source_url: Sourced<String>,
    pub state_oracle: Sourced<String>,
    pub state_oracle_deployment_block: Sourced<u64>,
}

/// Wraps a resolved value together with its provenance.
#[derive(Clone, PartialEq, Eq)]
pub struct Sourced<T> {
    pub value: T,
    pub source: Source,
}

impl<T: fmt::Debug> fmt::Debug for Sourced<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{:?} (from {:?})", self.value, self.source)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Source {
    Cli,
    Env,
    File,
}

// ---------------------------------------------------------------------------
// 4. Merge logic — CLI > ENV > FILE
// ---------------------------------------------------------------------------

#[derive(Debug)]
pub enum MergeError {
    Missing(String),
}

impl fmt::Display for MergeError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            MergeError::Missing(field) => {
                write!(f, "missing required config field: {field}")
            }
        }
    }
}

/// Merge CLI/ENV (from clap) with FILE config.
///
/// Uses `ArgMatches::value_source()` to determine provenance:
/// - `ValueSource::CommandLine` -> CLI flag was passed explicitly
/// - `ValueSource::EnvVariable` -> value came from an env var (via clap `env`)
/// - anything else (or None)     -> fall through to file value
pub fn merge(
    cli: &PocCliArgs,
    matches: &clap::ArgMatches,
    file: &PocFileConfig,
) -> Result<PocConfig, MergeError> {
    let chain_file = file.chain.as_ref().cloned().unwrap_or_default();
    let cred_file = file.credible.as_ref().cloned().unwrap_or_default();

    // NOTE: clap's derive macro uses the Rust field name (underscores) as the internal
    // arg ID. The kebab-case `--chain-id` is only the CLI flag; for `value_source()`
    // and `get_one()` we must use the underscore form.
    Ok(PocConfig {
        chain_id: resolve_field(
            "chain_id",
            matches,
            "chain_id",
            cli.chain_id,
            chain_file.chain_id,
        )?,
        spec_id: resolve_field(
            "spec_id",
            matches,
            "spec_id",
            cli.spec_id.clone(),
            chain_file.spec_id,
        )?,
        assertion_gas_limit: resolve_field(
            "assertion_gas_limit",
            matches,
            "assertion_gas_limit",
            cli.assertion_gas_limit,
            cred_file.assertion_gas_limit,
        )?,
        assertion_da_rpc_url: resolve_field(
            "assertion_da_rpc_url",
            matches,
            "assertion_da_rpc_url",
            cli.assertion_da_rpc_url.clone(),
            cred_file.assertion_da_rpc_url,
        )?,
        event_source_url: resolve_field(
            "event_source_url",
            matches,
            "event_source_url",
            cli.event_source_url.clone(),
            cred_file.event_source_url,
        )?,
        state_oracle: resolve_field(
            "state_oracle",
            matches,
            "state_oracle",
            cli.state_oracle.clone(),
            cred_file.state_oracle,
        )?,
        state_oracle_deployment_block: resolve_field(
            "state_oracle_deployment_block",
            matches,
            "state_oracle_deployment_block",
            cli.state_oracle_deployment_block,
            cred_file.state_oracle_deployment_block,
        )?,
    })
}

/// Resolve a single field using the precedence: CLI > ENV > FILE.
///
/// `clap_id` is the arg ID that clap uses internally — for derive macros this is the
/// Rust field name with underscores (e.g. `"chain_id"`), NOT the kebab-case flag.
fn resolve_field<T: Clone>(
    field_name: &str,
    matches: &clap::ArgMatches,
    clap_id: &str,
    cli_value: Option<T>,
    file_value: Option<T>,
) -> Result<Sourced<T>, MergeError> {
    // Check what clap thinks the source is for this argument.
    let source = matches.value_source(clap_id);

    match source {
        Some(ValueSource::CommandLine) => {
            // Explicit CLI flag — highest priority.
            Ok(Sourced {
                value: cli_value.unwrap(), // safe: clap wouldn't say CommandLine without a value
                source: Source::Cli,
            })
        }
        Some(ValueSource::EnvVariable) => {
            // Value came from an env var via clap's `env = "..."`.
            Ok(Sourced {
                value: cli_value.unwrap(), // safe: clap parsed the env value into this field
                source: Source::Env,
            })
        }
        _ => {
            // Not provided via CLI or ENV — fall back to file config.
            match file_value {
                Some(v) => Ok(Sourced {
                    value: v,
                    source: Source::File,
                }),
                None => Err(MergeError::Missing(field_name.to_string())),
            }
        }
    }
}

// ---------------------------------------------------------------------------
// 5. Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex;

    /// Global lock so env-var tests don't race each other.
    static ENV_LOCK: Mutex<()> = Mutex::new(());

    /// Helper: build `PocCliArgs` + `ArgMatches` from raw CLI tokens,
    /// without touching the real process args.
    fn parse_from(args: &[&str]) -> (PocCliArgs, clap::ArgMatches) {
        use clap::CommandFactory;

        // Build the clap Command from the derived struct, then parse.
        let cmd = PocCliArgs::command();
        let matches = cmd.get_matches_from(args);

        // Reconstruct the typed struct from the matches.
        // clap derive uses the Rust field name (underscores) as the arg ID.
        let cli = PocCliArgs {
            chain_id: matches.get_one::<u64>("chain_id").copied(),
            spec_id: matches.get_one::<String>("spec_id").cloned(),
            assertion_gas_limit: matches.get_one::<u64>("assertion_gas_limit").copied(),
            assertion_da_rpc_url: matches.get_one::<String>("assertion_da_rpc_url").cloned(),
            event_source_url: matches.get_one::<String>("event_source_url").cloned(),
            state_oracle: matches.get_one::<String>("state_oracle").cloned(),
            state_oracle_deployment_block: matches
                .get_one::<u64>("state_oracle_deployment_block")
                .copied(),
            config_file_path: matches.get_one::<String>("config_file_path").cloned(),
        };

        (cli, matches)
    }

    fn full_file_config() -> PocFileConfig {
        PocFileConfig {
            chain: Some(PocChainFile {
                chain_id: Some(1337),
                spec_id: Some("CANCUN".to_string()),
            }),
            credible: Some(PocCredibleFile {
                assertion_gas_limit: Some(3_000_000),
                assertion_da_rpc_url: Some("http://file-da:5001".to_string()),
                event_source_url: Some("http://file-events:4350/graphql".to_string()),
                state_oracle: Some("0x1111111111111111111111111111111111111111".to_string()),
                state_oracle_deployment_block: Some(100),
            }),
        }
    }

    // -----------------------------------------------------------------------
    // Test 1: FILE only — values come from JSON when no CLI/ENV
    // -----------------------------------------------------------------------
    #[test]
    fn test_file_only_values() {
        let _lock = ENV_LOCK.lock().unwrap();

        // Clear any env vars that clap might pick up.
        let env_keys = [
            "SIDECAR_CHAIN_ID",
            "SIDECAR_CHAIN_SPEC_ID",
            "SIDECAR_ASSERTION_GAS_LIMIT",
            "SIDECAR_ASSERTION_DA_RPC_URL",
            "SIDECAR_EVENT_SOURCE_URL",
            "SIDECAR_STATE_ORACLE",
            "SIDECAR_STATE_ORACLE_DEPLOYMENT_BLOCK",
        ];
        for key in &env_keys {
            unsafe { std::env::remove_var(key) };
        }

        // Parse with no CLI args (just the binary name).
        let (cli, matches) = parse_from(&["sidecar"]);
        let file = full_file_config();

        let cfg = merge(&cli, &matches, &file).expect("merge should succeed");

        // All values should come from FILE.
        assert_eq!(cfg.chain_id.value, 1337);
        assert_eq!(cfg.chain_id.source, Source::File);

        assert_eq!(cfg.spec_id.value, "CANCUN");
        assert_eq!(cfg.spec_id.source, Source::File);

        assert_eq!(cfg.assertion_gas_limit.value, 3_000_000);
        assert_eq!(cfg.assertion_gas_limit.source, Source::File);

        assert_eq!(cfg.assertion_da_rpc_url.value, "http://file-da:5001");
        assert_eq!(cfg.assertion_da_rpc_url.source, Source::File);

        assert_eq!(
            cfg.event_source_url.value,
            "http://file-events:4350/graphql"
        );
        assert_eq!(cfg.event_source_url.source, Source::File);

        assert_eq!(
            cfg.state_oracle.value,
            "0x1111111111111111111111111111111111111111"
        );
        assert_eq!(cfg.state_oracle.source, Source::File);

        assert_eq!(cfg.state_oracle_deployment_block.value, 100);
        assert_eq!(cfg.state_oracle_deployment_block.source, Source::File);

        // Provenance debug output:
        println!("\n=== Provenance (FILE only) ===");
        println!("  chain_id:           {:?}", cfg.chain_id);
        println!("  spec_id:            {:?}", cfg.spec_id);
        println!("  assertion_gas_limit:{:?}", cfg.assertion_gas_limit);
        println!("  da_rpc_url:         {:?}", cfg.assertion_da_rpc_url);
        println!("  event_source_url:   {:?}", cfg.event_source_url);
        println!("  state_oracle:       {:?}", cfg.state_oracle);
        println!(
            "  oracle_deploy_blk:  {:?}",
            cfg.state_oracle_deployment_block
        );
    }

    // -----------------------------------------------------------------------
    // Test 2: ENV overrides FILE
    // -----------------------------------------------------------------------
    #[test]
    fn test_env_overrides_file() {
        let _lock = ENV_LOCK.lock().unwrap();

        // Set env vars for chain_id and assertion_gas_limit only.
        unsafe {
            std::env::set_var("SIDECAR_CHAIN_ID", "42161");
            std::env::set_var("SIDECAR_ASSERTION_GAS_LIMIT", "9999999");
        }
        // Make sure other vars are clean.
        unsafe {
            std::env::remove_var("SIDECAR_CHAIN_SPEC_ID");
            std::env::remove_var("SIDECAR_ASSERTION_DA_RPC_URL");
            std::env::remove_var("SIDECAR_EVENT_SOURCE_URL");
            std::env::remove_var("SIDECAR_STATE_ORACLE");
            std::env::remove_var("SIDECAR_STATE_ORACLE_DEPLOYMENT_BLOCK");
        }

        let (cli, matches) = parse_from(&["sidecar"]);
        let file = full_file_config();
        let cfg = merge(&cli, &matches, &file).expect("merge should succeed");

        // ENV overrides file for these two fields:
        assert_eq!(cfg.chain_id.value, 42161);
        assert_eq!(cfg.chain_id.source, Source::Env);

        assert_eq!(cfg.assertion_gas_limit.value, 9999999);
        assert_eq!(cfg.assertion_gas_limit.source, Source::Env);

        // Other fields still come from FILE:
        assert_eq!(cfg.spec_id.value, "CANCUN");
        assert_eq!(cfg.spec_id.source, Source::File);

        assert_eq!(cfg.assertion_da_rpc_url.source, Source::File);

        // Clean up.
        unsafe {
            std::env::remove_var("SIDECAR_CHAIN_ID");
            std::env::remove_var("SIDECAR_ASSERTION_GAS_LIMIT");
        }

        println!("\n=== Provenance (ENV overrides FILE) ===");
        println!("  chain_id:            {:?}", cfg.chain_id);
        println!("  spec_id:             {:?}", cfg.spec_id);
        println!("  assertion_gas_limit: {:?}", cfg.assertion_gas_limit);
        println!("  da_rpc_url:          {:?}", cfg.assertion_da_rpc_url);
    }

    // -----------------------------------------------------------------------
    // Test 3: CLI overrides ENV and FILE
    // -----------------------------------------------------------------------
    #[test]
    fn test_cli_overrides_env_and_file() {
        let _lock = ENV_LOCK.lock().unwrap();

        // ENV sets chain_id to 42161.
        unsafe {
            std::env::set_var("SIDECAR_CHAIN_ID", "42161");
        }
        // Clean others.
        unsafe {
            std::env::remove_var("SIDECAR_CHAIN_SPEC_ID");
            std::env::remove_var("SIDECAR_ASSERTION_GAS_LIMIT");
            std::env::remove_var("SIDECAR_ASSERTION_DA_RPC_URL");
            std::env::remove_var("SIDECAR_EVENT_SOURCE_URL");
            std::env::remove_var("SIDECAR_STATE_ORACLE");
            std::env::remove_var("SIDECAR_STATE_ORACLE_DEPLOYMENT_BLOCK");
        }

        // CLI passes --chain-id 1 and --assertion-da-rpc-url.
        let (cli, matches) = parse_from(&[
            "sidecar",
            "--chain-id",
            "1",
            "--assertion-da-rpc-url",
            "http://cli-da:9999",
        ]);
        let file = full_file_config();
        let cfg = merge(&cli, &matches, &file).expect("merge should succeed");

        // CLI wins over ENV for chain_id:
        assert_eq!(cfg.chain_id.value, 1);
        assert_eq!(cfg.chain_id.source, Source::Cli);

        // CLI wins over FILE for assertion_da_rpc_url:
        assert_eq!(cfg.assertion_da_rpc_url.value, "http://cli-da:9999");
        assert_eq!(cfg.assertion_da_rpc_url.source, Source::Cli);

        // Other fields still come from FILE:
        assert_eq!(cfg.spec_id.source, Source::File);
        assert_eq!(cfg.assertion_gas_limit.source, Source::File);
        assert_eq!(cfg.event_source_url.source, Source::File);

        // Clean up.
        unsafe {
            std::env::remove_var("SIDECAR_CHAIN_ID");
        }

        println!("\n=== Provenance (CLI overrides ENV + FILE) ===");
        println!("  chain_id:        {:?}", cfg.chain_id);
        println!("  spec_id:         {:?}", cfg.spec_id);
        println!("  gas_limit:       {:?}", cfg.assertion_gas_limit);
        println!("  da_rpc_url:      {:?}", cfg.assertion_da_rpc_url);
        println!("  event_source:    {:?}", cfg.event_source_url);
        println!("  state_oracle:    {:?}", cfg.state_oracle);
        println!("  oracle_block:    {:?}", cfg.state_oracle_deployment_block);
    }

    // -----------------------------------------------------------------------
    // Test 4: missing required field errors
    // -----------------------------------------------------------------------
    #[test]
    fn test_missing_required_field_errors() {
        let _lock = ENV_LOCK.lock().unwrap();

        // Clear all env vars.
        let env_keys = [
            "SIDECAR_CHAIN_ID",
            "SIDECAR_CHAIN_SPEC_ID",
            "SIDECAR_ASSERTION_GAS_LIMIT",
            "SIDECAR_ASSERTION_DA_RPC_URL",
            "SIDECAR_EVENT_SOURCE_URL",
            "SIDECAR_STATE_ORACLE",
            "SIDECAR_STATE_ORACLE_DEPLOYMENT_BLOCK",
        ];
        for key in &env_keys {
            unsafe { std::env::remove_var(key) };
        }

        let (cli, matches) = parse_from(&["sidecar"]);
        // Empty file config — nothing provided anywhere.
        let file = PocFileConfig::default();

        let result = merge(&cli, &matches, &file);
        assert!(result.is_err());

        let err = result.unwrap_err();
        println!("Expected error: {err}");
        assert!(err.to_string().contains("missing required config field"));
    }

    // -----------------------------------------------------------------------
    // Test 5: provenance is reported correctly for mixed sources
    // -----------------------------------------------------------------------
    #[test]
    fn test_provenance_mixed_sources() {
        let _lock = ENV_LOCK.lock().unwrap();

        // ENV provides spec_id and event_source_url.
        unsafe {
            std::env::set_var("SIDECAR_CHAIN_SPEC_ID", "SHANGHAI");
            std::env::set_var("SIDECAR_EVENT_SOURCE_URL", "http://env-events:1234");
        }
        // Clean the rest.
        unsafe {
            std::env::remove_var("SIDECAR_CHAIN_ID");
            std::env::remove_var("SIDECAR_ASSERTION_GAS_LIMIT");
            std::env::remove_var("SIDECAR_ASSERTION_DA_RPC_URL");
            std::env::remove_var("SIDECAR_STATE_ORACLE");
            std::env::remove_var("SIDECAR_STATE_ORACLE_DEPLOYMENT_BLOCK");
        }

        // CLI provides chain_id.
        let (cli, matches) = parse_from(&["sidecar", "--chain-id", "10"]);
        let file = full_file_config();
        let cfg = merge(&cli, &matches, &file).expect("merge should succeed");

        // Verify mixed provenance:
        assert_eq!(cfg.chain_id.source, Source::Cli); // from CLI
        assert_eq!(cfg.chain_id.value, 10);

        assert_eq!(cfg.spec_id.source, Source::Env); // from ENV
        assert_eq!(cfg.spec_id.value, "SHANGHAI");

        assert_eq!(cfg.event_source_url.source, Source::Env); // from ENV
        assert_eq!(cfg.event_source_url.value, "http://env-events:1234");

        assert_eq!(cfg.assertion_gas_limit.source, Source::File); // from FILE
        assert_eq!(cfg.assertion_da_rpc_url.source, Source::File); // from FILE
        assert_eq!(cfg.state_oracle.source, Source::File); // from FILE
        assert_eq!(cfg.state_oracle_deployment_block.source, Source::File); // from FILE

        // Clean up.
        unsafe {
            std::env::remove_var("SIDECAR_CHAIN_SPEC_ID");
            std::env::remove_var("SIDECAR_EVENT_SOURCE_URL");
        }

        println!("\n=== Provenance (mixed CLI + ENV + FILE) ===");
        println!("  chain_id:        {:?}", cfg.chain_id);
        println!("  spec_id:         {:?}", cfg.spec_id);
        println!("  gas_limit:       {:?}", cfg.assertion_gas_limit);
        println!("  da_rpc_url:      {:?}", cfg.assertion_da_rpc_url);
        println!("  event_source:    {:?}", cfg.event_source_url);
        println!("  state_oracle:    {:?}", cfg.state_oracle);
        println!("  oracle_block:    {:?}", cfg.state_oracle_deployment_block);
    }
}
