global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'coordinator-docker'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'coordinator:9545' ]

  - job_name: 'coordinator-local'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'host.docker.internal:9546' ]

  - job_name: 'prover'
    static_configs:
      - targets: [ 'prover:9090' ]

  - job_name: 'credible-sidecar'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'credible-sidecar:9000' ]

  - job_name: 'assertion-da'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'assertion-da:9000' ]
