name: Docker GHCR Push - Assertion DA

on:
  push:
    branches: [main]
    tags:
      - "*.*.*"
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  check-version:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: Check version matches tag
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          CARGO_VERSION=$(grep -m 1 '^version = ' Cargo.toml | cut -d '"' -f2)
          if [ "$TAG_VERSION" != "$CARGO_VERSION" ]; then
            echo "Version mismatch: Tag version ($TAG_VERSION) does not match workspace Cargo.toml version ($CARGO_VERSION)"
            exit 1
          fi
  docker-ghcr-push:
    needs: check-version
    if: always() && (needs.check-version.result == 'success' || needs.check-version.result == 'skipped')
    uses: phylaxsystems/actions/.github/workflows/release-docker-ghcr.yaml@main
    with:
      rust-binary-name: assertion-da
      requires-private-deps: false
      dockerfile-path: dockerfile/Dockerfile.da
  docker-ghcr-push-dev:
    needs: check-version
    if: always() && (needs.check-version.result == 'success' || needs.check-version.result == 'skipped')
    uses: phylaxsystems/actions/.github/workflows/release-docker-ghcr.yaml@main
    with:
      rust-binary-name: assertion-da-dev
      requires-private-deps: false
      dockerfile-path: dockerfile/Dockerfile.da
      build-flags: "--features debug_assertions"